spring.application.name=concesionaria-api
server.port=${PORT:8081}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@localhost:1521:XE}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:concesionaria}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:pass123}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


app.jwt.secret=${APP_JWT_SECRET:ConcesionariaSecretKeyParaJWT2026MuySegura1234567890}
