--------------------------------------------------------
-- Archivo creado  - miércoles-agosto-19-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ADMINISTRADOR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CONCESIONARIA"."ADMINISTRADOR_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE
--------------------------------------------------------
--  DDL for Sequence CLIENTE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CONCESIONARIA"."CLIENTE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE
--------------------------------------------------------
--  DDL for Sequence DISPONIBILIDAD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CONCESIONARIA"."DISPONIBILIDAD_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE
--------------------------------------------------------
--  DDL for Sequence MARCA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CONCESIONARIA"."MARCA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE
--------------------------------------------------------
--  DDL for Sequence SOLICITUDATENCION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CONCESIONARIA"."SOLICITUDATENCION_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE
--------------------------------------------------------
--  DDL for Table ADMINISTRADORES
--------------------------------------------------------

  CREATE TABLE "CONCESIONARIA"."ADMINISTRADORES" 
   (	"ID_ADMINISTRADOR" NUMBER(19,0) NOT NULL ENABLE, 
	"USUARIO" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"CONTRASENA" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"CORREO" VARCHAR2(120 CHAR) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_ADMINISTRADOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 UNIQUE ("USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 UNIQUE ("CORREO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"
--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "CONCESIONARIA"."CLIENTES" 
   (	"ID_CLIENTE" NUMBER(19,0) NOT NULL ENABLE, 
	"DOCUMENTO" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"TELEFONO" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"APELLIDO" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"CIUDAD" VARCHAR2(80 CHAR), 
	"NOMBRE" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"CORREO" VARCHAR2(120 CHAR), 
	"CONTRASENA" VARCHAR2(100 CHAR), 
	"USUARIO" VARCHAR2(50 CHAR), 
	"ESTADO" VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 UNIQUE ("DOCUMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "UKRTYX66VBW29MP93LOUVS0GHS" UNIQUE ("USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"
--------------------------------------------------------
--  DDL for Table DISPONIBILIDADES
--------------------------------------------------------

  CREATE TABLE "CONCESIONARIA"."DISPONIBILIDADES" 
   (	"FECHA" DATE NOT NULL ENABLE, 
	"HORA_FIN" TIMESTAMP (0) NOT NULL ENABLE, 
	"HORA_INICIO" TIMESTAMP (0) NOT NULL ENABLE, 
	"ASESOR_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ID_DISPONIBILIDAD" NUMBER(19,0) NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_DISPONIBILIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FKP0F7QQPP4TBS0EGBXJDH25W7J" FOREIGN KEY ("ASESOR_ID")
	  REFERENCES "CONCESIONARIA"."ASESORES" ("ID_ASESOR") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"
--------------------------------------------------------
--  DDL for Table MARCAS
--------------------------------------------------------

  CREATE TABLE "CONCESIONARIA"."MARCAS" 
   (	"ID_MARCA" NUMBER(19,0) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_MARCA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 UNIQUE ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"
--------------------------------------------------------
--  DDL for Table SOLICITUDES_ATENCION
--------------------------------------------------------

  CREATE TABLE "CONCESIONARIA"."SOLICITUDES_ATENCION" 
   (	"FECHA_ATENCION" DATE NOT NULL ENABLE, 
	"HORA_ATENCION" TIMESTAMP (0) NOT NULL ENABLE, 
	"ASESOR_ID" NUMBER(19,0), 
	"CLIENTE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"DISPONIBILIDAD_ID" NUMBER(19,0), 
	"FECHA_SOLICITUD" TIMESTAMP (9) NOT NULL ENABLE, 
	"ID_SOLICITUD" NUMBER(19,0) NOT NULL ENABLE, 
	"VEHICULO_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"TIPO_ATENCION" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_SOLICITUD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FKAWCKDRJNG9X0YV2U9H4BEQDOE" FOREIGN KEY ("ASESOR_ID")
	  REFERENCES "CONCESIONARIA"."ASESORES" ("ID_ASESOR") ENABLE, 
	 CONSTRAINT "FKQM5HDQTVQ331H73TKDNW6YUXS" FOREIGN KEY ("CLIENTE_ID")
	  REFERENCES "CONCESIONARIA"."CLIENTES" ("ID_CLIENTE") ENABLE, 
	 CONSTRAINT "FKQ6NU7U3PD7L5W8DY8VUFR9C5A" FOREIGN KEY ("DISPONIBILIDAD_ID")
	  REFERENCES "CONCESIONARIA"."DISPONIBILIDADES" ("ID_DISPONIBILIDAD") ENABLE, 
	 CONSTRAINT "FK19ME81Q1HJKQY4VLIKMTQ9SQW" FOREIGN KEY ("VEHICULO_ID")
	  REFERENCES "CONCESIONARIA"."VEHICULOS" ("ID_VEHICULO") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"
REM INSERTING into CONCESIONARIA.ADMINISTRADORES
SET DEFINE OFF;
Insert into CONCESIONARIA.ADMINISTRADORES (ID_ADMINISTRADOR,USUARIO,CONTRASENA,NOMBRE,CORREO) values ('1','admin','$2a$10$Wtx2oCxVdRJuF8bhR2avUuT8hSJatBTa1aM/5/X5Psd6VqzglNedG','Administrador Principal','admin@concesionaria.com');
REM INSERTING into CONCESIONARIA.ASESORES
SET DEFINE OFF;
Insert into CONCESIONARIA.ASESORES (CONCESIONARIA_ID,ID_ASESOR,ESTADO,TELEFONO,APELLIDO,NOMBRE,ESPECIALIDAD,CORREO,HORA_FIN_TRABAJO,HORA_INICIO_TRABAJO,CONTRASENA,USUARIO) values ('1','1','ACTIVO','3001112233','Pérez','Carlos','Vehículos Toyota','carlos@concesionaria.com',to_timestamp('01/01/70 06:00:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),to_timestamp('01/01/70 08:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'$2a$10$873DZqvgr58CuAZ4ZLzYGe2JMXrGGj1QZAXvCZ/hj2cPD7djvBHpW','carlosperez');
Insert into CONCESIONARIA.ASESORES (CONCESIONARIA_ID,ID_ASESOR,ESTADO,TELEFONO,APELLIDO,NOMBRE,ESPECIALIDAD,CORREO,HORA_FIN_TRABAJO,HORA_INICIO_TRABAJO,CONTRASENA,USUARIO) values ('1','2','ACTIVO','3004445566','Gómez','Laura','Vehículos Chevrolet','laura@concesionaria.com',to_timestamp('01/01/70 06:00:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),to_timestamp('01/01/70 08:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'$2a$10$zbFQYxfv.lpDD2x7roDE6OGDtAlUcEMP58KtCdztjzYtHpSUPukBu','lauragomez');
Insert into CONCESIONARIA.ASESORES (CONCESIONARIA_ID,ID_ASESOR,ESTADO,TELEFONO,APELLIDO,NOMBRE,ESPECIALIDAD,CORREO,HORA_FIN_TRABAJO,HORA_INICIO_TRABAJO,CONTRASENA,USUARIO) values ('1','3','INACTIVO','3007771122','Martínez','Andrés','Vehículos Mazda','andres@concesionaria.com',to_timestamp('01/01/70 06:00:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),to_timestamp('01/01/70 08:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'$2a$10$oGEbpveUztyOktC/ZuzWe.MqJ666WwFAYTVQJVUmowU54./5D49R6','andresmartinez');
REM INSERTING into CONCESIONARIA.CLIENTES
SET DEFINE OFF;
Insert into CONCESIONARIA.CLIENTES (ID_CLIENTE,DOCUMENTO,TELEFONO,APELLIDO,CIUDAD,NOMBRE,CORREO,CONTRASENA,USUARIO,ESTADO) values ('1','1000000001','3009998877','Pérez','Cereté','Juan','juan@example.com','$2a$10$4Ky9dxvFgQcbLJgqPxDJluC0JLo3c1iqAEGl5N5mzjg/E6jyWY.fu','cliente1000000001','ACTIVO');
Insert into CONCESIONARIA.CLIENTES (ID_CLIENTE,DOCUMENTO,TELEFONO,APELLIDO,CIUDAD,NOMBRE,CORREO,CONTRASENA,USUARIO,ESTADO) values ('2','1000000456','3015557788','Rodríguez','Montería','Daniel','daniel.rodriguez@gmail.com','$2a$10$pSP.H4TXk//DIz5rf3JRc.tpFdkCbQpxeE1VlimPfR4sCZQVTyRwq','cliente1000000456','ACTIVO');
Insert into CONCESIONARIA.CLIENTES (ID_CLIENTE,DOCUMENTO,TELEFONO,APELLIDO,CIUDAD,NOMBRE,CORREO,CONTRASENA,USUARIO,ESTADO) values ('3','1104867789','3022100833','otero','tolú','santiago','ftydytty@bugug.com','$2a$10$NDsPauBGqth8kgFeDXmALOLnQwydeun/c8Kach.Xq5N4gROKnSzJa','cliente1104867789','ACTIVO');
Insert into CONCESIONARIA.CLIENTES (ID_CLIENTE,DOCUMENTO,TELEFONO,APELLIDO,CIUDAD,NOMBRE,CORREO,CONTRASENA,USUARIO,ESTADO) values ('4','1327277227','3145195831','corcho','tolú','rivi','sjisjisj@jushs.com','$2a$10$tuOstSuXhAeUdS8YnrdhhOBVhjQZOv/u6QRkggrmXZuji3/3.KRzq','cliente1327277227','ACTIVO');
Insert into CONCESIONARIA.CLIENTES (ID_CLIENTE,DOCUMENTO,TELEFONO,APELLIDO,CIUDAD,NOMBRE,CORREO,CONTRASENA,USUARIO,ESTADO) values ('5','44829589','3022100833','otero','tolú','atixto','theotercoc@gmail.com','$2a$10$wBHllBcr8INCogt4kd7Oa.u6jwfZxOqwuG/iu6ntGi9cOxNQ7oWge','atix','ACTIVO');
REM INSERTING into CONCESIONARIA.CONCESIONARIAS
SET DEFINE OFF;
Insert into CONCESIONARIA.CONCESIONARIAS (ID_CONCESIONARIA,TELEFONO,CORREO,NOMBRE,HORARIO_ATENCION,DIRECCION) values ('1','3001234567','info@concesionariacentral.com','Concesionaria Central','Lunes a sábado de 8:00 AM a 6:00 PM','Carrera 10 # 20-30');
REM INSERTING into CONCESIONARIA.DISPONIBILIDADES
SET DEFINE OFF;
Insert into CONCESIONARIA.DISPONIBILIDADES (FECHA,HORA_FIN,HORA_INICIO,ASESOR_ID,ID_DISPONIBILIDAD,ESTADO) values (to_date('13/08/26','DD/MM/RR'),to_timestamp('01/01/70 10:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),to_timestamp('01/01/70 09:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'1','1','DISPONIBLE');
Insert into CONCESIONARIA.DISPONIBILIDADES (FECHA,HORA_FIN,HORA_INICIO,ASESOR_ID,ID_DISPONIBILIDAD,ESTADO) values (to_date('13/08/26','DD/MM/RR'),to_timestamp('01/01/70 11:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),to_timestamp('01/01/70 10:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'1','2','DISPONIBLE');
Insert into CONCESIONARIA.DISPONIBILIDADES (FECHA,HORA_FIN,HORA_INICIO,ASESOR_ID,ID_DISPONIBILIDAD,ESTADO) values (to_date('13/08/26','DD/MM/RR'),to_timestamp('01/01/70 10:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),to_timestamp('01/01/70 09:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'2','3','DISPONIBLE');
Insert into CONCESIONARIA.DISPONIBILIDADES (FECHA,HORA_FIN,HORA_INICIO,ASESOR_ID,ID_DISPONIBILIDAD,ESTADO) values (to_date('13/08/26','DD/MM/RR'),to_timestamp('01/01/70 12:00:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),to_timestamp('01/01/70 11:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'2','4','OCUPADA');
Insert into CONCESIONARIA.DISPONIBILIDADES (FECHA,HORA_FIN,HORA_INICIO,ASESOR_ID,ID_DISPONIBILIDAD,ESTADO) values (to_date('25/08/26','DD/MM/RR'),to_timestamp('01/01/70 03:00:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),to_timestamp('01/01/70 02:00:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'3','5','OCUPADA');
REM INSERTING into CONCESIONARIA.FINANCIACIONES
SET DEFINE OFF;
Insert into CONCESIONARIA.FINANCIACIONES (PLAZO,PORCENTAJE_INICIAL,CONCESIONARIA_ID,ID_FINANCIACION,NOMBRE,CONDICIONES,DESCRIPCION) values ('60','20','1','1','Plan estándar','Sujeto a estudio y aprobación de crédito.','Financiación para compra de vehículo nuevo.');
REM INSERTING into CONCESIONARIA.MARCAS
SET DEFINE OFF;
Insert into CONCESIONARIA.MARCAS (ID_MARCA,NOMBRE) values ('2','Chevrolet');
Insert into CONCESIONARIA.MARCAS (ID_MARCA,NOMBRE) values ('1','Toyota');
REM INSERTING into CONCESIONARIA.MODELOS
SET DEFINE OFF;
Insert into CONCESIONARIA.MODELOS (ID_MODELO,MARCA_ID,NOMBRE) values ('1','1','Corolla');
Insert into CONCESIONARIA.MODELOS (ID_MODELO,MARCA_ID,NOMBRE) values ('2','1','Hilux');
Insert into CONCESIONARIA.MODELOS (ID_MODELO,MARCA_ID,NOMBRE) values ('3','2','Onix');
REM INSERTING into CONCESIONARIA.SOLICITUDES_ATENCION
SET DEFINE OFF;
Insert into CONCESIONARIA.SOLICITUDES_ATENCION (FECHA_ATENCION,HORA_ATENCION,ASESOR_ID,CLIENTE_ID,DISPONIBILIDAD_ID,FECHA_SOLICITUD,ID_SOLICITUD,VEHICULO_ID,ESTADO,TIPO_ATENCION) values (to_date('19/08/26','DD/MM/RR'),to_timestamp('01/01/70 05:00:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'1','5',null,to_timestamp('19/08/26 04:32:44,764241200 PM','DD/MM/RR HH12:MI:SSXFF AM'),'17','1','ATENDIENDO','Asesoría para compra de vehículo');
REM INSERTING into CONCESIONARIA.VEHICULOS
SET DEFINE OFF;
Insert into CONCESIONARIA.VEHICULOS (ANIO,PRECIO,CONCESIONARIA_ID,ID_VEHICULO,MODELO_ID,ESTADO,COLOR,COMBUSTIBLE,TRANSMISION,TIPO,MOTOR,DESCRIPCION,ALTO,ANCHO,CAPACIDAD_BAUL,CILINDRADA,EQUIPAMIENTO,IMAGEN_URL,LARGO,PASAJEROS,PESO,POTENCIA,SEGURIDAD,TORQUE,TRACCION,RENDIMIENTO) values ('2026','98000000','1','1','1','DISPONIBLE','Blanco','Gasolina','Automática','Sedán','2.0L','Vehículo familiar de excelente rendimiento','1.435 mm','1.780 mm','371 L','1.987 cc','Pantalla multimedia; Bluetooth; Apple CarPlay/Android Auto; aire acondicionado','https://commons.wikimedia.org/wiki/Special:FilePath/2025_Toyota_Corolla_LE_ice_cap.jpg','4.630 mm','5','1.390 kg','169 hp','7 airbags; ABS con EBD; control de estabilidad; cámara de reversa','200 Nm','Delantera (FWD)','Según versión y condiciones de conducción');
Insert into CONCESIONARIA.VEHICULOS (ANIO,PRECIO,CONCESIONARIA_ID,ID_VEHICULO,MODELO_ID,ESTADO,COLOR,COMBUSTIBLE,TRANSMISION,TIPO,MOTOR,DESCRIPCION,ALTO,ANCHO,CAPACIDAD_BAUL,CILINDRADA,EQUIPAMIENTO,IMAGEN_URL,LARGO,PASAJEROS,PESO,POTENCIA,SEGURIDAD,TORQUE,TRACCION,RENDIMIENTO) values ('2025','175000000','1','2','2','DISPONIBLE','Gris','Diesel','Automática','Pickup','2.8L','Pickup para trabajo y uso personal','1.815 mm','1.855 mm','Caja de carga','2.755 cc','Pantalla multimedia; cámara de reversa; aire acondicionado; control crucero','https://commons.wikimedia.org/wiki/Special:FilePath/Toyota_Hilux_4x2_V_Conquest_2025.jpg','5.325 mm','5','2.125 kg','201 hp','7 airbags; ABS; control de estabilidad; control de tracción; asistencia de descenso','500 Nm','4x4','Según versión y condiciones de conducción');
Insert into CONCESIONARIA.VEHICULOS (ANIO,PRECIO,CONCESIONARIA_ID,ID_VEHICULO,MODELO_ID,ESTADO,COLOR,COMBUSTIBLE,TRANSMISION,TIPO,MOTOR,DESCRIPCION,ALTO,ANCHO,CAPACIDAD_BAUL,CILINDRADA,EQUIPAMIENTO,IMAGEN_URL,LARGO,PASAJEROS,PESO,POTENCIA,SEGURIDAD,TORQUE,TRACCION,RENDIMIENTO) values ('2026','76000000','1','3','3','DISPONIBLE','Rojo','Gasolina','Automática','Sedán','1.0L Turbo','Sedán compacto y eficiente','1.476 mm','1.730 mm','469 L','999 cc Turbo','Pantalla multimedia; Bluetooth; Apple CarPlay/Android Auto; aire acondicionado','https://commons.wikimedia.org/wiki/Special:FilePath/Chevrolet_Onix_Turbo_RS_2024.jpg','4.163 mm','5','1.112 kg','115 hp','6 airbags; ABS; control de estabilidad; asistente de arranque en pendiente; cámara de reversa','160 Nm','Delantera (FWD)','Según versión y condiciones de conducción');
--------------------------------------------------------
--  DDL for Index UKRTYX66VBW29MP93LOUVS0GHS
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONCESIONARIA"."UKRTYX66VBW29MP93LOUVS0GHS" ON "CONCESIONARIA"."CLIENTES" ("USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"
--------------------------------------------------------
--  Constraints for Table ASESORES
--------------------------------------------------------

  ALTER TABLE "CONCESIONARIA"."ASESORES" MODIFY ("CONCESIONARIA_ID" NOT NULL ENABLE)
 
  ALTER TABLE "CONCESIONARIA"."ASESORES" MODIFY ("ID_ASESOR" NOT NULL ENABLE)
 
  ALTER TABLE "CONCESIONARIA"."ASESORES" MODIFY ("ESTADO" NOT NULL ENABLE)
 
  ALTER TABLE "CONCESIONARIA"."ASESORES" MODIFY ("TELEFONO" NOT NULL ENABLE)
 
  ALTER TABLE "CONCESIONARIA"."ASESORES" MODIFY ("APELLIDO" NOT NULL ENABLE)
 
  ALTER TABLE "CONCESIONARIA"."ASESORES" MODIFY ("NOMBRE" NOT NULL ENABLE)
 
  ALTER TABLE "CONCESIONARIA"."ASESORES" ADD PRIMARY KEY ("ID_ASESOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
 
  ALTER TABLE "CONCESIONARIA"."ASESORES" ADD CONSTRAINT "UKJFE30OLLD87WHTSBKX69V5SDD" UNIQUE ("USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
--------------------------------------------------------
--  Constraints for Table VEHICULOS
--------------------------------------------------------

  ALTER TABLE "CONCESIONARIA"."VEHICULOS" MODIFY ("ANIO" NOT NULL ENABLE)
 
  ALTER TABLE "CONCESIONARIA"."VEHICULOS" MODIFY ("PRECIO" NOT NULL ENABLE)
 
  ALTER TABLE "CONCESIONARIA"."VEHICULOS" MODIFY ("CONCESIONARIA_ID" NOT NULL ENABLE)
 
  ALTER TABLE "CONCESIONARIA"."VEHICULOS" MODIFY ("ID_VEHICULO" NOT NULL ENABLE)
 
  ALTER TABLE "CONCESIONARIA"."VEHICULOS" MODIFY ("MODELO_ID" NOT NULL ENABLE)
 
  ALTER TABLE "CONCESIONARIA"."VEHICULOS" MODIFY ("ESTADO" NOT NULL ENABLE)
 
  ALTER TABLE "CONCESIONARIA"."VEHICULOS" MODIFY ("COLOR" NOT NULL ENABLE)
 
  ALTER TABLE "CONCESIONARIA"."VEHICULOS" MODIFY ("COMBUSTIBLE" NOT NULL ENABLE)
 
  ALTER TABLE "CONCESIONARIA"."VEHICULOS" MODIFY ("TRANSMISION" NOT NULL ENABLE)
 
  ALTER TABLE "CONCESIONARIA"."VEHICULOS" MODIFY ("TIPO" NOT NULL ENABLE)
 
  ALTER TABLE "CONCESIONARIA"."VEHICULOS" MODIFY ("MOTOR" NOT NULL ENABLE)
 
  ALTER TABLE "CONCESIONARIA"."VEHICULOS" ADD CHECK ((anio>=1900)) ENABLE
 
  ALTER TABLE "CONCESIONARIA"."VEHICULOS" ADD PRIMARY KEY ("ID_VEHICULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
 
  ALTER TABLE "CONCESIONARIA"."VEHICULOS" ADD CHECK ((pasajeros>=1)) ENABLE
--------------------------------------------------------
--  Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "CONCESIONARIA"."CLIENTES" MODIFY ("ID_CLIENTE" NOT NULL ENABLE)
 
  ALTER TABLE "CONCESIONARIA"."CLIENTES" MODIFY ("DOCUMENTO" NOT NULL ENABLE)
 
  ALTER TABLE "CONCESIONARIA"."CLIENTES" MODIFY ("TELEFONO" NOT NULL ENABLE)
 
  ALTER TABLE "CONCESIONARIA"."CLIENTES" MODIFY ("APELLIDO" NOT NULL ENABLE)
 
  ALTER TABLE "CONCESIONARIA"."CLIENTES" MODIFY ("NOMBRE" NOT NULL ENABLE)
 
  ALTER TABLE "CONCESIONARIA"."CLIENTES" ADD PRIMARY KEY ("ID_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
 
  ALTER TABLE "CONCESIONARIA"."CLIENTES" ADD UNIQUE ("DOCUMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
 
  ALTER TABLE "CONCESIONARIA"."CLIENTES" MODIFY ("ESTADO" NOT NULL ENABLE)
 
  ALTER TABLE "CONCESIONARIA"."CLIENTES" ADD CONSTRAINT "UKRTYX66VBW29MP93LOUVS0GHS" UNIQUE ("USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
--------------------------------------------------------
--  Constraints for Table MARCAS
--------------------------------------------------------

  ALTER TABLE "CONCESIONARIA"."MARCAS" MODIFY ("ID_MARCA" NOT NULL ENABLE)
 
  ALTER TABLE "CONCESIONARIA"."MARCAS" MODIFY ("NOMBRE" NOT NULL ENABLE)
 
  ALTER TABLE "CONCESIONARIA"."MARCAS" ADD PRIMARY KEY ("ID_MARCA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
 
  ALTER TABLE "CONCESIONARIA"."MARCAS" ADD UNIQUE ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
--------------------------------------------------------
--  Constraints for Table ADMINISTRADORES
--------------------------------------------------------

  ALTER TABLE "CONCESIONARIA"."ADMINISTRADORES" MODIFY ("ID_ADMINISTRADOR" NOT NULL ENABLE)
 
  ALTER TABLE "CONCESIONARIA"."ADMINISTRADORES" MODIFY ("USUARIO" NOT NULL ENABLE)
 
  ALTER TABLE "CONCESIONARIA"."ADMINISTRADORES" MODIFY ("CONTRASENA" NOT NULL ENABLE)
 
  ALTER TABLE "CONCESIONARIA"."ADMINISTRADORES" MODIFY ("NOMBRE" NOT NULL ENABLE)
 
  ALTER TABLE "CONCESIONARIA"."ADMINISTRADORES" MODIFY ("CORREO" NOT NULL ENABLE)
 
  ALTER TABLE "CONCESIONARIA"."ADMINISTRADORES" ADD PRIMARY KEY ("ID_ADMINISTRADOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
 
  ALTER TABLE "CONCESIONARIA"."ADMINISTRADORES" ADD UNIQUE ("USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
 
  ALTER TABLE "CONCESIONARIA"."ADMINISTRADORES" ADD UNIQUE ("CORREO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
--------------------------------------------------------
--  Ref Constraints for Table ASESORES
--------------------------------------------------------

  ALTER TABLE "CONCESIONARIA"."ASESORES" ADD CONSTRAINT "FK6B6KDLBIA0OS23OCUF1LFCDYR" FOREIGN KEY ("CONCESIONARIA_ID")
	  REFERENCES "CONCESIONARIA"."CONCESIONARIAS" ("ID_CONCESIONARIA") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table FINANCIACIONES
--------------------------------------------------------

  ALTER TABLE "CONCESIONARIA"."FINANCIACIONES" ADD CONSTRAINT "FK67SE447QMAMESSHMGW4VA7P4J" FOREIGN KEY ("CONCESIONARIA_ID")
	  REFERENCES "CONCESIONARIA"."CONCESIONARIAS" ("ID_CONCESIONARIA") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table SOLICITUDES_ATENCION
--------------------------------------------------------

  ALTER TABLE "CONCESIONARIA"."SOLICITUDES_ATENCION" ADD CONSTRAINT "FK19ME81Q1HJKQY4VLIKMTQ9SQW" FOREIGN KEY ("VEHICULO_ID")
	  REFERENCES "CONCESIONARIA"."VEHICULOS" ("ID_VEHICULO") ENABLE
 
  ALTER TABLE "CONCESIONARIA"."SOLICITUDES_ATENCION" ADD CONSTRAINT "FKAWCKDRJNG9X0YV2U9H4BEQDOE" FOREIGN KEY ("ASESOR_ID")
	  REFERENCES "CONCESIONARIA"."ASESORES" ("ID_ASESOR") ENABLE
 
  ALTER TABLE "CONCESIONARIA"."SOLICITUDES_ATENCION" ADD CONSTRAINT "FKQ6NU7U3PD7L5W8DY8VUFR9C5A" FOREIGN KEY ("DISPONIBILIDAD_ID")
	  REFERENCES "CONCESIONARIA"."DISPONIBILIDADES" ("ID_DISPONIBILIDAD") ENABLE
 
  ALTER TABLE "CONCESIONARIA"."SOLICITUDES_ATENCION" ADD CONSTRAINT "FKQM5HDQTVQ331H73TKDNW6YUXS" FOREIGN KEY ("CLIENTE_ID")
	  REFERENCES "CONCESIONARIA"."CLIENTES" ("ID_CLIENTE") ENABLE
