-- ============================================================
-- MIGRACION NITIDA - CONCESIONARIA CENTRAL
-- Ejecutar UNA sola vez sobre la base actual de Oracle.
-- Requiere estar conectado al esquema CONCESIONARIA (o al esquema
-- que contiene CLIENTES, ASESORES, VEHICULOS, FINANCIACIONES, etc.).
-- ============================================================

-- 1. Columnas necesarias en clientes y atenciones
DECLARE n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM USER_TAB_COLUMNS WHERE TABLE_NAME='CLIENTES' AND COLUMN_NAME='ESTADO';
  IF n=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE CLIENTES ADD (ESTADO VARCHAR2(20) DEFAULT ''ACTIVO'' NOT NULL)'; END IF;

  SELECT COUNT(*) INTO n FROM USER_TAB_COLUMNS WHERE TABLE_NAME='SOLICITUDES_ATENCION' AND COLUMN_NAME='FECHA_INICIO_ATENCION';
  IF n=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE SOLICITUDES_ATENCION ADD (FECHA_INICIO_ATENCION TIMESTAMP)'; END IF;

  SELECT COUNT(*) INTO n FROM USER_TAB_COLUMNS WHERE TABLE_NAME='SOLICITUDES_ATENCION' AND COLUMN_NAME='FECHA_FIN_ATENCION';
  IF n=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE SOLICITUDES_ATENCION ADD (FECHA_FIN_ATENCION TIMESTAMP)'; END IF;
END;
/

-- 2. Las secuencias nuevas se crean después de las tablas.

-- 3. Tablas del flujo comercial
DECLARE n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM USER_TABLES WHERE TABLE_NAME='OPORTUNIDADES';
  IF n=0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE OPORTUNIDADES (
        ID_OPORTUNIDAD NUMBER(19) PRIMARY KEY,
        CLIENTE_ID NUMBER(19) NOT NULL,
        ASESOR_ID NUMBER(19) NOT NULL,
        VEHICULO_ID NUMBER(19) NOT NULL,
        SOLICITUD_ATENCION_ID NUMBER(19) NOT NULL UNIQUE,
        ESTADO VARCHAR2(30) DEFAULT 'INTERESADO' NOT NULL,
        PRESUPUESTO NUMBER(14,2),
        FORMA_PAGO VARCHAR2(30),
        FINANCIACION_ID NUMBER(19),
        OBSERVACIONES VARCHAR2(1000),
        MOTIVO_PERDIDA VARCHAR2(300),
        FECHA_CREACION TIMESTAMP NOT NULL,
        FECHA_ACTUALIZACION TIMESTAMP NOT NULL,
        CONSTRAINT FK_OPORT_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID_CLIENTE),
        CONSTRAINT FK_OPORT_ASESOR FOREIGN KEY (ASESOR_ID) REFERENCES ASESORES(ID_ASESOR),
        CONSTRAINT FK_OPORT_VEHICULO FOREIGN KEY (VEHICULO_ID) REFERENCES VEHICULOS(ID_VEHICULO),
        CONSTRAINT FK_OPORT_SOLICITUD FOREIGN KEY (SOLICITUD_ATENCION_ID) REFERENCES SOLICITUDES_ATENCION(ID_SOLICITUD),
        CONSTRAINT FK_OPORT_FINAN FOREIGN KEY (FINANCIACION_ID) REFERENCES FINANCIACIONES(ID_FINANCIACION)
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO n FROM USER_TABLES WHERE TABLE_NAME='SEGUIMIENTOS';
  IF n=0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE SEGUIMIENTOS (
        ID_SEGUIMIENTO NUMBER(19) PRIMARY KEY,
        OPORTUNIDAD_ID NUMBER(19) NOT NULL,
        FECHA_PROGRAMADA DATE NOT NULL,
        MEDIO VARCHAR2(30) NOT NULL,
        ESTADO VARCHAR2(30) DEFAULT 'PENDIENTE' NOT NULL,
        RESULTADO VARCHAR2(40),
        OBSERVACIONES VARCHAR2(1000),
        FECHA_REALIZADO TIMESTAMP,
        CONSTRAINT FK_SEG_OPORTUNIDAD FOREIGN KEY (OPORTUNIDAD_ID) REFERENCES OPORTUNIDADES(ID_OPORTUNIDAD)
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO n FROM USER_TABLES WHERE TABLE_NAME='VENTAS';
  IF n=0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE VENTAS (
        ID_VENTA NUMBER(19) PRIMARY KEY,
        OPORTUNIDAD_ID NUMBER(19) NOT NULL UNIQUE,
        CLIENTE_ID NUMBER(19) NOT NULL,
        ASESOR_ID NUMBER(19) NOT NULL,
        VEHICULO_ID NUMBER(19) NOT NULL,
        PRECIO_FINAL NUMBER(14,2) NOT NULL,
        FORMA_PAGO VARCHAR2(30) NOT NULL,
        FINANCIACION_ID NUMBER(19),
        FECHA_VENTA DATE NOT NULL,
        CONSTRAINT FK_VENTA_OPORT FOREIGN KEY (OPORTUNIDAD_ID) REFERENCES OPORTUNIDADES(ID_OPORTUNIDAD),
        CONSTRAINT FK_VENTA_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID_CLIENTE),
        CONSTRAINT FK_VENTA_ASESOR FOREIGN KEY (ASESOR_ID) REFERENCES ASESORES(ID_ASESOR),
        CONSTRAINT FK_VENTA_VEHICULO FOREIGN KEY (VEHICULO_ID) REFERENCES VEHICULOS(ID_VEHICULO),
        CONSTRAINT FK_VENTA_FINAN FOREIGN KEY (FINANCIACION_ID) REFERENCES FINANCIACIONES(ID_FINANCIACION)
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO n FROM USER_TABLES WHERE TABLE_NAME='SOLICITUDES_FINANCIACION';
  IF n=0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE SOLICITUDES_FINANCIACION (
        ID_SOLICITUD_FINANCIACION NUMBER(19) PRIMARY KEY,
        OPORTUNIDAD_ID NUMBER(19) NOT NULL UNIQUE,
        FINANCIACION_ID NUMBER(19) NOT NULL,
        MONTO_VEHICULO NUMBER(14,2) NOT NULL,
        CUOTA_INICIAL NUMBER(14,2) NOT NULL,
        MONTO_SOLICITADO NUMBER(14,2) NOT NULL,
        PLAZO_MESES NUMBER(10) NOT NULL,
        ESTADO VARCHAR2(30) DEFAULT 'PENDIENTE' NOT NULL,
        OBSERVACIONES VARCHAR2(1000),
        FECHA_SOLICITUD TIMESTAMP NOT NULL,
        FECHA_ACTUALIZACION TIMESTAMP NOT NULL,
        CONSTRAINT FK_SOLFIN_OPORT FOREIGN KEY (OPORTUNIDAD_ID) REFERENCES OPORTUNIDADES(ID_OPORTUNIDAD),
        CONSTRAINT FK_SOLFIN_PLAN FOREIGN KEY (FINANCIACION_ID) REFERENCES FINANCIACIONES(ID_FINANCIACION)
      )
    ]';
  END IF;
END;
/

-- 4. Crear secuencias que pudieron quedar pendientes por crearse antes
DECLARE n NUMBER; v_start NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM USER_SEQUENCES WHERE SEQUENCE_NAME='OPORTUNIDAD_SEQ';
  IF n=0 THEN SELECT NVL(MAX(ID_OPORTUNIDAD),0)+1 INTO v_start FROM OPORTUNIDADES; EXECUTE IMMEDIATE 'CREATE SEQUENCE OPORTUNIDAD_SEQ START WITH '||v_start||' INCREMENT BY 1'; END IF;
  SELECT COUNT(*) INTO n FROM USER_SEQUENCES WHERE SEQUENCE_NAME='SEGUIMIENTO_SEQ';
  IF n=0 THEN SELECT NVL(MAX(ID_SEGUIMIENTO),0)+1 INTO v_start FROM SEGUIMIENTOS; EXECUTE IMMEDIATE 'CREATE SEQUENCE SEGUIMIENTO_SEQ START WITH '||v_start||' INCREMENT BY 1'; END IF;
  SELECT COUNT(*) INTO n FROM USER_SEQUENCES WHERE SEQUENCE_NAME='VENTA_SEQ';
  IF n=0 THEN SELECT NVL(MAX(ID_VENTA),0)+1 INTO v_start FROM VENTAS; EXECUTE IMMEDIATE 'CREATE SEQUENCE VENTA_SEQ START WITH '||v_start||' INCREMENT BY 1'; END IF;
  SELECT COUNT(*) INTO n FROM USER_SEQUENCES WHERE SEQUENCE_NAME='SOLICITUD_FINANCIACION_SEQ';
  IF n=0 THEN SELECT NVL(MAX(ID_SOLICITUD_FINANCIACION),0)+1 INTO v_start FROM SOLICITUDES_FINANCIACION; EXECUTE IMMEDIATE 'CREATE SEQUENCE SOLICITUD_FINANCIACION_SEQ START WITH '||v_start||' INCREMENT BY 1'; END IF;
END;
/

-- 5. Índices para consultas frecuentes
DECLARE n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM USER_INDEXES WHERE INDEX_NAME='IDX_OPORT_ASESOR';
  IF n=0 THEN EXECUTE IMMEDIATE 'CREATE INDEX IDX_OPORT_ASESOR ON OPORTUNIDADES(ASESOR_ID)'; END IF;
  SELECT COUNT(*) INTO n FROM USER_INDEXES WHERE INDEX_NAME='IDX_OPORT_CLIENTE';
  IF n=0 THEN EXECUTE IMMEDIATE 'CREATE INDEX IDX_OPORT_CLIENTE ON OPORTUNIDADES(CLIENTE_ID)'; END IF;
  SELECT COUNT(*) INTO n FROM USER_INDEXES WHERE INDEX_NAME='IDX_OPORT_ESTADO';
  IF n=0 THEN EXECUTE IMMEDIATE 'CREATE INDEX IDX_OPORT_ESTADO ON OPORTUNIDADES(ESTADO)'; END IF;
  SELECT COUNT(*) INTO n FROM USER_INDEXES WHERE INDEX_NAME='IDX_SEG_FECHA';
  IF n=0 THEN EXECUTE IMMEDIATE 'CREATE INDEX IDX_SEG_FECHA ON SEGUIMIENTOS(FECHA_PROGRAMADA)'; END IF;
  SELECT COUNT(*) INTO n FROM USER_INDEXES WHERE INDEX_NAME='IDX_SOLFIN_ESTADO';
  IF n=0 THEN EXECUTE IMMEDIATE 'CREATE INDEX IDX_SOLFIN_ESTADO ON SOLICITUDES_FINANCIACION(ESTADO)'; END IF;
END;
/

COMMIT;

-- 6. Verificación
SELECT TABLE_NAME FROM USER_TABLES
WHERE TABLE_NAME IN ('CLIENTES','SOLICITUDES_ATENCION','OPORTUNIDADES','SEGUIMIENTOS','VENTAS','FINANCIACIONES','SOLICITUDES_FINANCIACION')
ORDER BY TABLE_NAME;

SELECT TABLE_NAME,COLUMN_NAME FROM USER_TAB_COLUMNS
WHERE (TABLE_NAME='CLIENTES' AND COLUMN_NAME='ESTADO')
   OR (TABLE_NAME='SOLICITUDES_ATENCION' AND COLUMN_NAME IN ('FECHA_INICIO_ATENCION','FECHA_FIN_ATENCION'))
ORDER BY TABLE_NAME,COLUMN_NAME;
